import carLogos from './carLogos';
import compass from '../assets/compass.svg';

export default {
  iconCar: require('../assets/icon_car_white.png'),
  iconMap: require('../assets/icon_map_white.png'),
  iconRoad: require('../assets/icon_road_white.png'),
  iconClose: require('../assets/icon_close.png'),
  iconCheckmark: require('../assets/icon_checkmark.png'),
  iconChevronLeft: require('../assets/icon_chevron_left.png'),
  iconChevronDown: require('../assets/icon_chevron_down.png'),
  iconError: require('../assets/error-icon.png'),
  iconMinus: require('../assets/icon_minus.png'),
  iconPlusCircle: require('../assets/icon_plus_circle.png'),
  iconMyLocation: require('../assets/icon_my_location_white.png'),
  iconFuel: require('../assets/icon_fuel.png'),
  iconOil: require('../assets/icon_oil.png'),
  iconUser: require('../assets/icon_user.png'),
  iconSearch: require('../assets/icon_search_white.png'),
  iconPinParked: require('../assets/icon_pin_parked.png'),
  iconCog: require('../assets/icon_cog.png'),
  iconRefresh: require('../assets/icon_refresh.png'),
  iconStatusParked: require('../assets/icon_status_parked.png'),
  iconComma: require('../assets/icon_comma.png'),
  commaWhite: require('../assets/comma_white.png'),
  spinnerCircle: require('../assets/spinner_circle.png'),
  spinnerComma: require('../assets/spinner_comma.png'),
  drawingCar: require('../assets/drawing_car_01.png'),
  drawingKeys: require('../assets/drawing_keys_01.png'),
  drawingEon: require('../assets/drawing_eon_01.png'),
  drawingPanda: require('../assets/drawing_panda_01.png'),
  placeholderCar: require('../assets/placeholder_car_01.png'),
  applePayMark: require('../assets/applepay.png'),
  googlePayMark: require('../assets/googlepay.png'),
  photoSetupEonVideo: require('../assets/photo_installation_video_01.png'),
  carLogos: carLogos,
  Compass: compass,
  cardAmex: require('../assets/stp_card_amex.png'),
  cardDiners: require('../assets/stp_card_diners.png'),
  cardDiscover: require('../assets/stp_card_discover.png'),
  cardJcb: require('../assets/stp_card_jcb.png'),
  cardMastercard: require('../assets/stp_card_mastercard.png'),
  cardVisa: require('../assets/stp_card_visa.png'),
  cardUnknown: require('../assets/stp_card_unknown.png'),
  authGoogle: require('../assets/auth_google.png'),
  authApple: require('../assets/auth_apple.png'),
  authGithub: require('../assets/auth_google.png'),
}
