# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'connect' do

  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.9'
  pod 'GoogleSignIn'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


  pod 'lottie-ios', :podspec => '../node_modules/lottie-ios/lottie-ios.podspec'
  pod 'lottie-react-native', :podspec => '../node_modules/lottie-react-native/lottie-react-native.podspec'
  pod 'react-native-camera', :podspec => '../node_modules/react-native-camera/react-native-camera.podspec'
  pod 'react-native-mapbox-gl', :podspec => '../node_modules/@mapbox/react-native-mapbox-gl/react-native-mapbox-gl.podspec'
  pod 'react-native-video', :podspec => '../node_modules/react-native-video/react-native-video.podspec'
  pod 'ReactNativePermissions', :podspec => '../node_modules/react-native-permissions/ReactNativePermissions.podspec'
  pod 'rn-fetch-blob', :podspec => '../node_modules/rn-fetch-blob/rn-fetch-blob.podspec'
  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'
  pod 'RNAnalyticsIntegration-Mixpanel', :path => '../node_modules/@segment/analytics-react-native-mixpanel'
  pod 'RNDeviceInfo', :podspec => '../node_modules/react-native-device-info/RNDeviceInfo.podspec'
  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  pod 'RNGoogleSignin', :podspec => '../node_modules/react-native-google-signin/RNGoogleSignin.podspec'
  pod 'RNSentry', :podspec => '../node_modules/@sentry/react-native/RNSentry.podspec'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'react-native-ios-launch-arguments', :podspec => '../node_modules/react-native-ios-launch-arguments/react-native-ios-launch-arguments.podspec'
  pod 'tipsi-stripe', :podspec => '../node_modules/@commaai/tipsi-stripe/tipsi-stripe.podspec'

 end
