require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'connect' do
  use_native_modules!

  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.9'
  pod 'GoogleSignIn'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'lottie-ios', :podspec => '../node_modules/lottie-ios/lottie-ios.podspec'
  pod 'react-native-mapbox-gl', :podspec => '../node_modules/@mapbox/react-native-mapbox-gl/react-native-mapbox-gl.podspec'
  pod 'ReactNativePermissions', :podspec => '../node_modules/react-native-permissions/ReactNativePermissions.podspec'
  pod 'react-native-ios-launch-arguments', :podspec => '../node_modules/react-native-ios-launch-arguments/react-native-ios-launch-arguments.podspec'
  pod 'tipsi-stripe', :podspec => '../node_modules/@commaai/tipsi-stripe/tipsi-stripe.podspec'

 end
