name: build

on: [push]

jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Cache ruby dependencies
        uses: actions/cache@v1
        id: bundler-cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gemfile-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gemfile-
      - name: Cache node modules
        uses: actions/cache@v1
        id: node-cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Yarn Install
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Install bundler
        run: gem install bundler:2.2.14
      - name: Bundle setup
        run: bundle config path vendor/bundle
      - name: Bundle install
        if: steps.bundler-cache.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3
      - name: Build
        run: bundle exec fastlane android test_build
