name: build

on: [push]

jobs:
  run-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache ruby dependencies
        uses: actions/cache@v1
        id: bundler-cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gemfile-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gemfile-
      - name: Cache node modules
        uses: actions/cache@v1
        id: node-cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Cache pods
        uses: actions/cache@v1
        id: pod-cache
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Yarn Install
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Install bundler
        run: gem install bundler:2.2.14
      - name: Bundle setup
        run: bundle config path vendor/bundle
      - name: Bundle install
        if: steps.bundler-cache.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3
      - name: Bundle install ios
        if: steps.bundler-cache.outputs.cache-hit != 'true'
        working-directory: ios
        run: bundle install --jobs 4 --retry 3
      - name: Pods install
        working-directory: ios
        run: bundle exec pod cache clean --all && bundle exec pod repo update && bundle exec pod install
      - name: Build
        run: bundle exec fastlane ios build_for_testing
